name = "LowLevelParticleFilters"
uuid = "d9d29d28-c116-5dba-9239-57a5fe23875b"
authors = ["baggepinnen <baggepinnen@gmail.com>"]
version = "0.2.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Yeppp = "6310b701-1812-5374-a82f-9f6f2d54a40a"

[compat]
Distributions = "<0.22"
Parameters = "<0.13"
Lazy = "<0.15"
PDMats = "0.9"
Plots = "0.27"
StaticArrays = "<0.13"
StatsBase = "0.29,0.30,0.32"
Yeppp = "<0.5"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
